site_name: Reinno Pages
site_url: https://reinno.github.io/reinno-pages/
site_description: Observations of the subject [reinno].
site_author: Who am I? Just a curious observer.

theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.side.toc
    - revision.date
    - revision.history

nav:
  - Home: index.md
  - Blog:
    - "Observation Index": blog/index.md
    - "Observation Note #001": blog/2026/observation-note-001.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - meta

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - css/custom.css
